### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by toohappygirl** [tofuai/neoplasm-segmentation#3]
Could you please release your dataset here?

**Comment by tofuai** [comment]
Yes, we released the dataset on Kaggle. Please see here:
https://www.kaggle.com/competitions/bkai-igh-neopolyp/data

**Comment by toohappygirl** [comment]
I am very sorry to interrupt you again.I have found the link of your dataset releasedon Kaggle,but the dataset is not identical with that article referred to.
So I send you again to ask for the dataset which appeared in the BlazeNeo article.If there is any inconvenience,I am very sorry.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tofuai/neoplasm-segmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tofuai/neoplasm-segmentation] dataset (Issue #3)





 
Yes, we released the dataset on Kaggle. Please see here:
 https://www.kaggle.com/competitions/bkai-igh-neopolyp/data

**Comment by tofuai** [comment]
We regret that the dataset in the paper is private and the benchmark in the paper is not from the public dataset.
