### ISSUE TITLE
How do you deal with the pixel that belongs to none of these three classes?

### ISSUE THREAD

**Issue by toohappygirl** [tofuai/neoplasm-segmentation#4]
For exmaple,the mask has many pixels.It isn't (255,0,0) and it isn't (0,255,0), (255, 255, 0),(255, 255, 255) at the same time.Which class does this kind of pixel belong to?

**Comment by tofuai** [comment]
Sorry that I don't fully understand the question. There are two kind of mask, polyp mask and neoplastic mask. For the polyp mask, [255, 255, 255] is for the polyp pixel. And for the neoplastic mask, [255, 255, 0] is for the undefined pixel. You can read more of it in the link below. I'm sorry that I do not have time to refactor everything for easy understanding.

https://github.com/tofuai/blazeneo/blob/737cb9ef77c934a0bef4cc858c9e23192a6cfdf2/utils/data.py#L95
